# Generated by Django 2.2.13 on 2021-03-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='date',
            field=models.DateField(),
        ),
    ]
