# Generated by Django 2.2.13 on 2021-03-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20210325_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='billType',
            field=models.CharField(choices=[('Monthly Payments', 'Monthly Payments'), ('Personal', 'Personal'), ('Domestic', 'Domestic'), ('Travels', 'Travels'), ('Food', 'Food'), ('Entertainment', 'Entertainment')], default='Monthly Payments', max_length=255),
        ),
    ]
