# Generated by Django 2.2.13 on 2021-03-23 20:52

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20210322_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='eventDate',
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='eventDuration',
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='eventTime',
        ),
        migrations.AddField(
            model_name='schedules',
            name='eventEnd',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 20, 51, 32, 168540, tzinfo=utc), help_text='The end time must be later than the start time.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedules',
            name='eventStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
