# Generated by Django 2.2.13 on 2021-03-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20210318_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='lastProgress',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
