# Generated by Django 2.2.13 on 2021-03-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20210318_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='dueDate',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='mark_as_complete',
        ),
    ]
