# Generated by Django 2.2.13 on 2021-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20210312_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='mark_as_complete',
            field=models.BooleanField(default=False),
        ),
    ]
