# Generated by Django 2.2.13 on 2021-03-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_mark_as_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='taskDescription',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
